trigger:
  branches: 
    include:

    - main
    - develop
    - release/*

pool: Default


parameters: 
- name: targetEnv
  default: string
  values:

  - Dev
  - qa
  - UAT
  - Staging
  - Production

  